from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import ImageView, PlotWidget
        
        
def setup_standard(self, MainWindow): 
    self.centralwidget.setObjectName("centralwidget")
    self.frame = QtWidgets.QFrame(self.centralwidget)
    self.frame.setGeometry(QtCore.QRect(10, 10, 151, 241))
    self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame.setObjectName("frame")
    self.pushButton = QtWidgets.QPushButton(self.frame)
    self.pushButton.setGeometry(QtCore.QRect(20, 10, 111, 51))
    self.pushButton.setObjectName("pushButton")
    self.pushButton_2 = QtWidgets.QPushButton(self.frame)
    self.pushButton_2.setGeometry(QtCore.QRect(20, 70, 111, 51))
    self.pushButton_2.setObjectName("pushButton_2")
    self.pushButton_3 = QtWidgets.QPushButton(self.frame)
    self.pushButton_3.setGeometry(QtCore.QRect(20, 130, 111, 51))
    self.pushButton_3.setObjectName("pushButton_3")
    self.checkBox = QtWidgets.QCheckBox(self.frame)
    self.checkBox.setGeometry(QtCore.QRect(20, 190, 111, 41))
    font = QtGui.QFont()
    font.setFamily("Helvetica Neue")
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.checkBox.setFont(font)
    self.checkBox.setObjectName("checkBox")
    # self.frame_3 = QtWidgets.QFrame(self.centralwidget)
    # self.frame_3.setGeometry(QtCore.QRect(760, 20, 341, 241))
    # self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
    # self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
    # self.frame_3.setObjectName("frame_3")
    # self.slider = QtWidgets.QSlider(self.frame_3)
    # self.slider.setGeometry(QtCore.QRect(30, 70, 131, 22))
    # self.slider.setOrientation(QtCore.Qt.Horizontal)
    # self.slider.setObjectName("slider")
    self.label = QtWidgets.QLabel(self.frame_3)
    self.label.setGeometry(QtCore.QRect(20, 20, 171, 21))
    font = QtGui.QFont()
    font.setFamily("Helvetica Neue")
    font.setPointSize(18)
    font.setBold(True)
    font.setWeight(75)
    self.label.setFont(font)
    self.label.setObjectName("label")
    self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
    self.pushButton_4.setGeometry(QtCore.QRect(30, 190, 115, 32))
    font = QtGui.QFont()
    font.setFamily("Helvetica Neue")
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.pushButton_4.setFont(font)
    self.pushButton_4.setObjectName("pushButton_4")
    self.label_6 = QtWidgets.QLabel(self.frame_3)
    self.label_6.setGeometry(QtCore.QRect(70, 90, 71, 21))
    font = QtGui.QFont()
    font.setFamily("Helvetica Neue")
    font.setPointSize(13)
    font.setBold(False)
    font.setWeight(50)
    self.label_6.setFont(font)
    self.label_6.setObjectName("label_6")
    self.label_7 = QtWidgets.QLabel(self.frame_3)
    self.label_7.setGeometry(QtCore.QRect(70, 140, 71, 21))
    font = QtGui.QFont()
    font.setFamily("Helvetica Neue")
    font.setPointSize(13)
    font.setBold(False)
    font.setWeight(50)
    self.label_7.setFont(font)
    self.label_7.setObjectName("label_7")
    # self.frame_10 = QtWidgets.QFrame(self.frame_3)
    # self.frame_10.setGeometry(QtCore.QRect(194, 64, 133, 125))
    # self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
    # self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
    # self.frame_10.setObjectName("frame_10")
    # self.grplot_5 = PlotWidget(self.frame_10)
    # self.grplot_5.setGeometry(QtCore.QRect(6, 6, 121, 113))
    # self.grplot_5.setObjectName("grplot_5")
    self.label_2 = QtWidgets.QLabel(self.centralwidget)
    self.label_2.setGeometry(QtCore.QRect(170, 10, 131, 21))
    font = QtGui.QFont()
    font.setFamily("Helvetica Neue")
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.label_2.setFont(font)
    self.label_2.setObjectName("label_2")
    self.label_3 = QtWidgets.QLabel(self.centralwidget)
    self.label_3.setGeometry(QtCore.QRect(170, 134, 131, 21))
    font = QtGui.QFont()
    font.setFamily("Helvetica Neue")
    font.setPointSize(14)
    font.setBold(True)
    font.setWeight(75)
    self.label_3.setFont(font)
    self.label_3.setObjectName("label_3")
    self.frame_6 = QtWidgets.QFrame(self.centralwidget)
    self.frame_6.setGeometry(QtCore.QRect(170, 30, 431, 101))
    self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame_6.setObjectName("frame_6")
    self.grplot = PlotWidget(self.frame_6)
    self.grplot.setGeometry(QtCore.QRect(6, 6, 419, 89))
    self.grplot.setObjectName("grplot")
    self.frame_8 = QtWidgets.QFrame(self.centralwidget)
    self.frame_8.setGeometry(QtCore.QRect(170, 154, 431, 101))
    self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
    self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
    self.frame_8.setObjectName("frame_8")
    self.grplot_2 = PlotWidget(self.frame_8)
    self.grplot_2.setGeometry(QtCore.QRect(6, 6, 419, 89))
    self.grplot_2.setObjectName("grplot_2")
    MainWindow.setCentralWidget(self.centralwidget)
    self.menubar = QtWidgets.QMenuBar(MainWindow)
    self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 20))
    self.menubar.setObjectName("menubar")
    self.menuRASP_Display = QtWidgets.QMenu(self.menubar)
    self.menuRASP_Display.setObjectName("menuRASP_Display")
    MainWindow.setMenuBar(self.menubar)
    self.statusbar = QtWidgets.QStatusBar(MainWindow)
    self.statusbar.setObjectName("statusbar")
    MainWindow.setStatusBar(self.statusbar)
    self.menubar.addAction(self.menuRASP_Display.menuAction())
    self.centralwidget = QtWidgets.QWidget(MainWindow)
    self.centralwidget.setObjectName("centralwidget")

    

    self.retranslateUi(MainWindow)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)
    