actors:
  Acquirer:
    package: improv.actors.acquire
    class: FileAcquirer
    filename: data/Tolias_mesoscope_2.hdf5
    framerate: 15

  Analysis:
    package: improv.actors.analysis
    class: MeanAnalysis

  InputStim:
    package: improv.actors.acquire
    class: BehaviorAcquirer

connections:
  Acquirer.q_out: [Analysis.q_in]
  InputStim.q_out: [Analysis.input_stim_queue]

# settings:
#   use_watcher: [Acquirer, Processor, Visual, Analysis]
