Acquirer: !!python/object:improv.tweak.TweakModule
  classname: FileAcquirer
  name: Acquirer
  options:
    filename: data/Tolias_mesoscope_2.hdf5
    framerate: 30
  packagename: improv.actors.acquire
Analysis: !!python/object:improv.tweak.TweakModule
  classname: MeanAnalysis
  name: Analysis
  options: {}
  packagename: improv.actors.analysis
Processor: !!python/object:improv.tweak.TweakModule
  classname: CaimanProcessor
  name: Processor
  options:
    config_file: caiman_params.txt
    init_filename: data/tbif_ex_crop.h5
  packagename: improv.actors.process
