actors:
  Acquirer:
    package: improv.actors.acquire
    class: FileAcquirer
    filename: data/Tolias_mesoscope_2.hdf5
    framerate: 30

  Processor:
    package: improv.actors.process
    class: CaimanProcessor

  Analysis:
    package: improv.actors.analysis
    class: MeanAnalysis

  InputStim:
    package: improv.actors.acquire
    class: BehaviorAcquirer


connections:
  Acquirer.q_out: [Processor.q_in]
  Acquirer.q_out: [Analysis.q_in]
  InputStim.q_out: [Analysis.input_stim_queue]
