actors:
  Acquirer:
    package: improv.actors.acquire
    class: FileAcquirer
    filename: data/Tolias_mesoscope_2.hdf5
    framerate: 15

  Analysis:
    package: improv.actors.analysis
    class: MeanAnalysis

connections:
  Acquirer.q_out: [Analysis.q_in]

# settings:
#   use_watcher: [Acquirer, Processor, Visual, Analysis]
