actors:
  Acquirer:
    package: improv.actors.acquire
    class: FileAcquirer
    filename: data/Tolias_mesoscope_2.hdf5
    framerate: 15

  Processor:
    package: demos.basic.actors.basic_processor
    class: BasicProcessor
    init_filename: data/Tolias_mesoscope_2.hdf5
    config_file: basic_caiman_params.txt

  Analysis:
    package: improv.actors.analysis
    class: MeanAnalysis

connections:
  Acquirer.q_out: [Processor.q_in,]
  Processor.q_out: [Analysis.q_in]

# settings:
#   use_watcher: [Acquirer, Processor, Visual, Analysis]
